(define (problem shape-stacking)
    (:domain shape-stacking)
    (:objects
        large-grey-rubber-cube large-grey-rubber-cylinder large-grey-rubber-sphere large-grey-metal-cube large-grey-metal-cylinder large-grey-metal-sphere large-red-rubber-cube large-red-rubber-cylinder large-red-rubber-sphere large-red-metal-cube large-red-metal-cylinder large-red-metal-sphere large-blue-rubber-cube large-blue-rubber-cylinder large-blue-rubber-sphere large-blue-metal-cube large-blue-metal-cylinder large-blue-metal-sphere large-green-rubber-cube large-green-rubber-cylinder large-green-rubber-sphere large-green-metal-cube large-green-metal-cylinder large-green-metal-sphere large-brown-rubber-cube large-brown-rubber-cylinder large-brown-rubber-sphere large-brown-metal-cube large-brown-metal-cylinder large-brown-metal-sphere large-purple-rubber-cube large-purple-rubber-cylinder large-purple-rubber-sphere large-purple-metal-cube large-purple-metal-cylinder large-purple-metal-sphere large-cyan-rubber-cube large-cyan-rubber-cylinder large-cyan-rubber-sphere large-cyan-metal-cube large-cyan-metal-cylinder large-cyan-metal-sphere large-yellow-rubber-cube large-yellow-rubber-cylinder large-yellow-rubber-sphere large-yellow-metal-cube large-yellow-metal-cylinder large-yellow-metal-sphere small-grey-rubber-cube small-grey-rubber-cylinder small-grey-rubber-sphere small-grey-metal-cube small-grey-metal-cylinder small-grey-metal-sphere small-red-rubber-cube small-red-rubber-cylinder small-red-rubber-sphere small-red-metal-cube small-red-metal-cylinder small-red-metal-sphere small-blue-rubber-cube small-blue-rubber-cylinder small-blue-rubber-sphere small-blue-metal-cube small-blue-metal-cylinder small-blue-metal-sphere small-green-rubber-cube small-green-rubber-cylinder small-green-rubber-sphere small-green-metal-cube small-green-metal-cylinder small-green-metal-sphere small-brown-rubber-cube small-brown-rubber-cylinder small-brown-rubber-sphere small-brown-metal-cube small-brown-metal-cylinder small-brown-metal-sphere small-purple-rubber-cube small-purple-rubber-cylinder small-purple-rubber-sphere small-purple-metal-cube small-purple-metal-cylinder small-purple-metal-sphere small-cyan-rubber-cube small-cyan-rubber-cylinder small-cyan-rubber-sphere small-cyan-metal-cube small-cyan-metal-cylinder small-cyan-metal-sphere small-yellow-rubber-cube small-yellow-rubber-cylinder small-yellow-rubber-sphere small-yellow-metal-cube small-yellow-metal-cylinder small-yellow-metal-sphere - block
    )

    (:init)
    (:goal (and))
)
